package com.example.dllo.mygiftproject.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.mygiftproject.db.LikeBean;

import com.example.dllo.mygiftproject.db.LikeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig likeBeanDaoConfig;

    private final LikeBeanDao likeBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);

        registerDao(LikeBean.class, likeBeanDao);
    }
    
    public void clear() {
        likeBeanDaoConfig.getIdentityScope().clear();
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

}
