package com.example.dllo.mygiftproject.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LIKE_BEAN".
 */
public class LikeBean {

    private Long id;
    private String userName;
    private String imageUrl;
    private String title;
    private String nextUrl;
    private String likesCount;
    private String other;
    private String path;

    public LikeBean() {
    }

    public LikeBean(Long id) {
        this.id = id;
    }

    public LikeBean(String path) {
        this.path = path;
    }

    public LikeBean(Long id, String userName, String imageUrl, String title, String nextUrl, String likesCount, String other, String path) {
        this.id = id;
        this.userName = userName;
        this.imageUrl = imageUrl;
        this.title = title;
        this.nextUrl = nextUrl;
        this.likesCount = likesCount;
        this.other = other;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNextUrl() {
        return nextUrl;
    }

    public void setNextUrl(String nextUrl) {
        this.nextUrl = nextUrl;
    }

    public String getLikesCount() {
        return likesCount;
    }

    public void setLikesCount(String likesCount) {
        this.likesCount = likesCount;
    }

    public String getOther() {
        return other;
    }

    public void setOther(String other) {
        this.other = other;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
