package com.example.dllo.mygiftproject.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.mygiftproject.db.LikeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIKE_BEAN".
*/
public class LikeBeanDao extends AbstractDao<LikeBean, Long> {

    public static final String TABLENAME = "LIKE_BEAN";

    /**
     * Properties of entity LikeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property ImageUrl = new Property(2, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property NextUrl = new Property(4, String.class, "nextUrl", false, "NEXT_URL");
        public final static Property LikesCount = new Property(5, String.class, "likesCount", false, "LIKES_COUNT");
        public final static Property Other = new Property(6, String.class, "other", false, "OTHER");
        public final static Property Path = new Property(7, String.class, "path", false, "PATH");
    };


    public LikeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LikeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIKE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"IMAGE_URL\" TEXT," + // 2: imageUrl
                "\"TITLE\" TEXT," + // 3: title
                "\"NEXT_URL\" TEXT," + // 4: nextUrl
                "\"LIKES_COUNT\" TEXT," + // 5: likesCount
                "\"OTHER\" TEXT," + // 6: other
                "\"PATH\" TEXT);"); // 7: path
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIKE_BEAN\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LikeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(3, imageUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String nextUrl = entity.getNextUrl();
        if (nextUrl != null) {
            stmt.bindString(5, nextUrl);
        }
 
        String likesCount = entity.getLikesCount();
        if (likesCount != null) {
            stmt.bindString(6, likesCount);
        }
 
        String other = entity.getOther();
        if (other != null) {
            stmt.bindString(7, other);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(8, path);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LikeBean readEntity(Cursor cursor, int offset) {
        LikeBean entity = new LikeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imageUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // nextUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // likesCount
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // other
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // path
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LikeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImageUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNextUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLikesCount(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOther(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPath(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LikeBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LikeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
